# Generated by Django 5.0.2 on 2024-02-08 17:46

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=sorl.thumbnail.fields.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
